---
- debug:
    msg: "Scope {{ ansible_os_family|lower }}_{{ ansible_distribution_major_version }}"
- include: debian-tasks.yml
  when: ansible_os_family == "Debian"

- name: include any specific tasks if needed
  include: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}_{{ ansible_distribution_major_version }}-tasks.yml"
      skip: true
